package main

import (
	"fmt"
	"image/color"
	"os"
	"path/filepath"
	"strings"
)

// The palette the shell draws with, fanned out to the apps that sit next to
// it. Before this, kitty and Thunar were frozen in Mocha while the bar
// followed the flavor picker and (with dynamic colours on) the wallpaper — so
// switching flavor recoloured the shell and left the terminal behind.
//
// This follows rofi.go: render a generated file and have the real config
// include it. The generated files are gitignored, because ~/.config/kitty and
// ~/.config/gtk-*.0 are symlinks into the repo — tracked, a customised palette
// would be an uncommitted change sitting in the way of every `git pull`. The
// committed `*.default.*` beside each one is the Mocha starting point, and
// apollo-doctor copies it into place on a fresh clone.

// flavorAccents is the accent family per flavor, mirroring the _flavors table
// in services/Config.qml. scripts/check-palettes.py fails the build if the two
// drift.
//
// Deliberately NOT part of flavorRamps: tintedPalette rewrites every hue in
// that map to a single wallpaper hue, which is right for neutral surfaces and
// wrong for accents. A terminal whose red, green and yellow are all the same
// hue cannot show a diff.
var flavorAccents = map[string]map[string]string{
	"mocha": {
		"rosewater": "#f5e0dc", "flamingo": "#f2cdcd", "pink": "#f5c2e7", "mauve": "#cba6f7",
		"red": "#f38ba8", "maroon": "#eba0ac", "peach": "#fab387", "yellow": "#f9e2af",
		"green": "#a6e3a1", "teal": "#94e2d5", "sky": "#89dceb", "sapphire": "#74c7ec",
		"blue": "#89b4fa", "lavender": "#b4befe",
	},
	"macchiato": {
		"rosewater": "#f4dbd6", "flamingo": "#f0c6c6", "pink": "#f5bde6", "mauve": "#c6a0f6",
		"red": "#ed8796", "maroon": "#ee99a0", "peach": "#f5a97f", "yellow": "#eed49f",
		"green": "#a6da95", "teal": "#8bd5ca", "sky": "#91d7e3", "sapphire": "#7dc4e4",
		"blue": "#8aadf4", "lavender": "#b7bdf8",
	},
	"frappe": {
		"rosewater": "#f2d5cf", "flamingo": "#eebebe", "pink": "#f4b8e4", "mauve": "#ca9ee6",
		"red": "#e78284", "maroon": "#ea999c", "peach": "#ef9f76", "yellow": "#e5c890",
		"green": "#a6d189", "teal": "#81c8be", "sky": "#99d1db", "sapphire": "#85c1dc",
		"blue": "#8caaee", "lavender": "#babbf1",
	},
	"latte": {
		"rosewater": "#dc8a78", "flamingo": "#dd7878", "pink": "#ea76cb", "mauve": "#8839ef",
		"red": "#d20f39", "maroon": "#e64553", "peach": "#fe640b", "yellow": "#df8e1d",
		"green": "#40a02b", "teal": "#179299", "sky": "#04a5e5", "sapphire": "#209fb5",
		"blue": "#1e66f5", "lavender": "#7287fd",
	},
}

// effectivePalette returns what the shell is actually drawing with: the
// flavor's neutral ramp, overridden slot by slot by a full dynamic palette
// when one is present, plus the flavor's accent family (which the wallpaper never
// touches).
//
// The override rule mirrors Config.qml's _p exactly, including the test for a
// non-empty base — an empty map and a map of empty strings both mean "no
// custom palette", and only the QML version of that rule is load-bearing at
// runtime, so this one has to agree with it.
func effectivePalette(c Config) map[string]string {
	flavor := c.Flavor
	if _, ok := flavorRamps[flavor]; !ok {
		flavor = "mocha"
	}
	out := make(map[string]string, 26)
	for k, v := range flavorRamps[flavor] {
		out[k] = v
	}
	for k, v := range flavorAccents[flavor] {
		out[k] = v
	}
	if c.Palette["base"] != "" {
		for k := range flavorRamps[flavor] {
			if v := c.Palette[k]; v != "" {
				out[k] = v
			}
		}
	}
	return out
}

// accentOr returns the user's accent, falling back to the flavor's mauve when
// it is unset — never to a literal, so an empty accent on Latte does not paint
// a Mocha purple onto a light palette.
func accentOr(c Config, p map[string]string) string {
	if strings.HasPrefix(c.Accent, "#") && len(c.Accent) == 7 {
		return c.Accent
	}
	return p["mauve"]
}

// ── kitty ────────────────────────────────────────────────────────────────

func kittyColorsPath() string {
	home, _ := os.UserHomeDir()
	return filepath.Join(home, ".config", "kitty", "apollo-colors.conf")
}

// renderKittyColors maps the palette onto kitty's names.
//
// One deliberate change from the hand-written kitty.conf this replaces: color0
// was the background (#1e1e2e), so anything printing in ANSI black was
// invisible. It is surface1 here, which is Catppuccin's own kitty mapping.
func renderKittyColors(c Config) string {
	p := effectivePalette(c)
	accent := accentOr(c, p)

	var b strings.Builder
	b.WriteString("# Generated by apollo-settings — DO NOT EDIT BY HAND.\n")
	b.WriteString("# Edit the palette in Apollo Settings › Theme; kitty.conf includes this.\n\n")

	put := func(k, v string) { fmt.Fprintf(&b, "%-24s %s\n", k, v) }

	put("background", p["base"])
	put("foreground", p["text"])
	put("cursor", p["rosewater"])
	put("cursor_text_color", p["base"])
	put("selection_foreground", p["base"])
	put("selection_background", p["rosewater"])
	put("url_color", p["rosewater"])
	b.WriteString("\n")
	// The window border and the active tab are where the accent knob shows up
	// in the terminal. Everything else here keeps the slot the hand-written
	// kitty.conf used, so this is the same terminal, following the palette.
	put("active_border_color", accent)
	put("inactive_border_color", p["overlay0"])
	put("active_tab_background", accent)
	put("active_tab_foreground", p["crust"])
	put("inactive_tab_background", p["mantle"])
	put("inactive_tab_foreground", p["text"])
	b.WriteString("\n# normal\n")
	for i, slot := range []string{"surface1", "red", "green", "yellow", "blue", "pink", "teal", "subtext1"} {
		put(fmt.Sprintf("color%d", i), p[slot])
	}
	b.WriteString("\n# bright\n")
	for i, slot := range []string{"surface2", "red", "green", "yellow", "blue", "pink", "teal", "subtext0"} {
		put(fmt.Sprintf("color%d", i+8), p[slot])
	}
	return b.String()
}

// ── GTK ──────────────────────────────────────────────────────────────────

func gtkColorsPath(major int) string {
	home, _ := os.UserHomeDir()
	return filepath.Join(home, ".config", fmt.Sprintf("gtk-%d.0", major), "apollo-colors.css")
}

// renderGtkColors defines the moon_* names gtk.css draws Thunar with. The
// translucent slots keep the alphas the hand-written stylesheet used — the
// file manager reads as glass over the blur, and that was a deliberate choice,
// not a side effect of the colours.
func renderGtkColors(c Config) string {
	p := effectivePalette(c)
	accent := accentOr(c, p)

	var b strings.Builder
	b.WriteString("/* Generated by apollo-settings — DO NOT EDIT BY HAND.\n")
	b.WriteString("   gtk.css imports this; edit the palette in Apollo Settings › Theme. */\n")
	fmt.Fprintf(&b, "@define-color moon_bg %s;\n", rgbaOf(p["crust"], 0.14))
	fmt.Fprintf(&b, "@define-color moon_panel %s;\n", rgbaOf(p["mantle"], 0.24))
	fmt.Fprintf(&b, "@define-color moon_panel_alt %s;\n", rgbaOf(p["surface0"], 0.22))
	fmt.Fprintf(&b, "@define-color moon_line %s;\n", rgbaOf(p["sky"], 0.26))
	fmt.Fprintf(&b, "@define-color moon_text %s;\n", p["text"])
	fmt.Fprintf(&b, "@define-color moon_muted %s;\n", p["overlay1"])
	fmt.Fprintf(&b, "@define-color moon_green %s;\n", p["green"])
	fmt.Fprintf(&b, "@define-color moon_cyan %s;\n", p["sky"])
	fmt.Fprintf(&b, "@define-color moon_mauve %s;\n", accent)
	return b.String()
}

// rgbaOf turns "#rrggbb" plus an alpha into GTK's rgba() form. GTK accepts
// #rrggbbaa in a colour literal but not inside @define-color on GTK3, so the
// functional form is the one that works in both.
func rgbaOf(hex string, alpha float64) string {
	nc := color.NRGBAModel.Convert(hexToColor(hex)).(color.NRGBA)
	return fmt.Sprintf("rgba(%d, %d, %d, %.2f)", nc.R, nc.G, nc.B, alpha)
}

// ── applying ─────────────────────────────────────────────────────────────

// applyApps writes every generated palette file. It is called from saveConfig
// rather than from an Apply button because the Theme tab's controls save
// directly — the flavor picker, the accent picker and dynamic colours all call
// saveConfig and rely on the shell noticing config.json change. Hanging the
// fan-out off the same write means no control can forget it.
func applyApps(c Config) error {
	files := map[string]string{
		kittyColorsPath(): renderKittyColors(c),
		gtkColorsPath(3):  renderGtkColors(c),
		gtkColorsPath(4):  renderGtkColors(c),
	}
	for path, body := range files {
		if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
			return err
		}
		if err := os.WriteFile(path, []byte(body), 0o644); err != nil {
			return err
		}
	}
	return nil
}
