package main

import (
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
)

// Apollo's Hyprland config is Lua, so this file writes a Lua module rather
// than the hyprlang fragment Moonlit generated. Three things changed with it:
//
//   - The generated file is ~/.config/hypr/lua/generated.lua, loaded from the
//     bottom of hyprland.lua. Being last is still what makes it win: repeated
//     hl.config() calls shadow earlier ones option by option.
//   - Overrides are hl.config() tables, not `general { ... }` blocks.
//   - Keybind overrides unbind by combo string: hl.unbind("SUPER + Q").
//
// The app keeps the user's combos in its own "MODS, KEY" form because the
// keybind UI (parseCombo/normCombo) is built around it. Translation to
// Hyprland's "MODS + KEY" happens here, at the boundary.

// hyprDir is ~/.config/hypr, honouring XDG_CONFIG_HOME if it's set.
func hyprDir() string {
	if xdg := os.Getenv("XDG_CONFIG_HOME"); xdg != "" {
		return filepath.Join(xdg, "hypr")
	}
	home, _ := os.UserHomeDir()
	return filepath.Join(home, ".config", "hypr")
}

// generatedLuaPath is the single file this app owns. Nothing else should write
// to it — every Apply overwrites it wholesale.
func generatedLuaPath() string {
	return filepath.Join(hyprDir(), "lua", "generated.lua")
}

// luaCombo turns the app's "SUPER SHIFT, Q" into Hyprland's "SUPER + SHIFT + Q".
// A combo with no modifiers ("", "XF86AudioMute") passes through as the bare key.
func luaCombo(combo string) string {
	mods, key := parseCombo(combo)

	// parseCombo returns a set, so fix an order rather than ranging the map:
	// map iteration is randomised and the generated file should be stable.
	var parts []string
	for _, m := range []string{"SUPER", "CTRL", "ALT", "SHIFT"} {
		if mods[m] {
			parts = append(parts, m)
		}
	}
	if key != "" {
		parts = append(parts, key)
	}
	return strings.Join(parts, " + ")
}

// luaString quotes a Go string as a Lua literal.
func luaString(s string) string {
	r := strings.NewReplacer(`\`, `\\`, `"`, `\"`, "\n", `\n`, "\r", `\r`)
	return `"` + r.Replace(s) + `"`
}

// renderHyprLua turns the app's Hyprland + keybind settings into a Lua module.
func renderHyprLua(c Config) string {
	var b strings.Builder
	b.WriteString("-- ─────────────────────────────────────────────────────────────\n")
	b.WriteString("-- Generated by apollo-settings — DO NOT EDIT BY HAND.\n")
	b.WriteString("-- Loaded last from hyprland.lua, so these values win.\n")
	b.WriteString("-- ─────────────────────────────────────────────────────────────\n\n")

	h := c.Hypr

	b.WriteString("hl.config({\n")
	b.WriteString("    general = {\n")
	fmt.Fprintf(&b, "        gaps_in     = %d,\n", h.GapsIn)
	fmt.Fprintf(&b, "        gaps_out    = %d,\n", h.GapsOut)
	fmt.Fprintf(&b, "        border_size = %d,\n", h.BorderSize)
	if h.BorderOverride {
		// A solid color replacing the base config's rotating gradient.
		b.WriteString("        col = {\n")
		fmt.Fprintf(&b, "            active_border   = \"rgb(%s)\",\n", strings.TrimPrefix(h.BorderActive, "#"))
		fmt.Fprintf(&b, "            inactive_border = \"rgb(%s)\",\n", strings.TrimPrefix(h.BorderInactive, "#"))
		b.WriteString("        },\n")
	}
	b.WriteString("    },\n\n")

	b.WriteString("    decoration = {\n")
	fmt.Fprintf(&b, "        rounding         = %d,\n", h.Rounding)
	fmt.Fprintf(&b, "        active_opacity   = %.2f,\n", h.ActiveOpacity)
	fmt.Fprintf(&b, "        inactive_opacity = %.2f,\n", h.InactiveOpacity)
	fmt.Fprintf(&b, "        blur   = { enabled = %t, size = %d },\n", h.BlurEnabled, h.BlurSize)
	fmt.Fprintf(&b, "        shadow = { enabled = %t },\n", h.ShadowEnabled)
	b.WriteString("    },\n\n")

	fmt.Fprintf(&b, "    animations = { enabled = %t },\n", h.AnimEnabled)
	b.WriteString("})\n")

	if len(c.Keybinds) > 0 {
		var lines []string
		// keybindOrder keeps the output deterministic; ranging the map would
		// reshuffle the file on every Apply and make diffs meaningless.
		for _, id := range keybindOrder {
			kb, ok := c.Keybinds[id]
			if !ok || kb.Combo == kb.Default {
				continue
			}
			lines = append(lines,
				fmt.Sprintf("hl.unbind(%s)\n", luaString(luaCombo(kb.Default))),
				fmt.Sprintf("hl.bind(%s, %s, { description = %s })\n",
					luaString(luaCombo(kb.Combo)), kb.Dispatcher, luaString(kb.Label)))
		}
		if len(lines) > 0 {
			b.WriteString("\n-- Keybind overrides (unbind the default, then rebind)\n")
			for _, l := range lines {
				b.WriteString(l)
			}
		}
	}

	return b.String()
}

// applyHypr writes generated.lua, makes sure hyprland.lua loads it, then
// reloads. This is the "hard change" path behind the Apply button.
func applyHypr(c Config) error {
	p := generatedLuaPath()
	if err := os.MkdirAll(filepath.Dir(p), 0o755); err != nil {
		return err
	}
	if err := os.WriteFile(p, []byte(renderHyprLua(c)), 0o644); err != nil {
		return err
	}
	if err := ensureLoaded(); err != nil {
		return err
	}
	out, err := exec.Command("hyprctl", "reload").CombinedOutput()
	if err != nil {
		return fmt.Errorf("hyprctl reload: %v: %s", err, strings.TrimSpace(string(out)))
	}
	return nil
}

// loadLine is what hyprland.lua needs at the bottom for the overrides to take
// effect. dofile rather than require: require caches by module name, so a
// second load in the same Lua state could serve a stale copy, while dofile
// always re-reads the file. pcall keeps a missing file from being an error.
const loadLine = `pcall(dofile, cfg_dir .. "/lua/generated.lua")`

// ensureLoaded appends the loader to hyprland.lua once, as the last lines so
// it overrides everything above it. Apollo's own hyprland.lua already has it;
// this is the safety net for a hand-written one.
func ensureLoaded() error {
	main := filepath.Join(hyprDir(), "hyprland.lua")
	data, err := os.ReadFile(main)
	if err != nil {
		return err
	}
	body := string(data)
	if strings.Contains(body, "lua/generated.lua") {
		return nil
	}
	if !strings.HasSuffix(body, "\n") {
		body += "\n"
	}
	body += "\n-- apollo-settings generated overrides (must stay last)\n" +
		"local cfg_dir = (os.getenv(\"XDG_CONFIG_HOME\") or ((os.getenv(\"HOME\") or \"\") .. \"/.config\")) .. \"/hypr\"\n" +
		loadLine + "\n"
	return os.WriteFile(main, []byte(body), 0o644)
}
