package main

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

// The login screen's share of the palette.
//
// SDDM's greeter runs as its own unprivileged user, whose home is
// /var/lib/sddm. It cannot read anything under /home/<you> — a mode 700 home
// directory is the Arch default — so the theme cannot simply point at the
// wallpaper or at a generated file in ~/.config. Everything it draws has to be
// copied into /usr/share/sddm/themes/apollo, which needs root.
//
// So this half only *stages* the colours. `apollo-sddm-sync` (root) is what
// puts them, and the current wallpaper, where the greeter can see them. That
// split is deliberate: nothing on the wallpaper hot path ever needs privileges,
// and the sync is a single command you can run by hand and watch.

// stagedLoginColorsPath is the [General] block apollo-sddm-sync copies into the
// installed theme's theme.conf.
func stagedLoginColorsPath() string {
	return filepath.Join(cacheHome(), "apollo", "theme", "sddm-colors.conf")
}

// readableOn returns the palette colour to draw *on top of* hex — the flavour's
// darkest neutral over a light accent, its lightest over a dark one. Material's
// on_* roles do the same thing; here the accent can be any colour the wallpaper
// yielded, so the choice has to be made rather than looked up.
func readableOn(hex string, p map[string]string) string {
	_, _, l := rgbToHSL(hexToColor(hex))
	if l > 0.55 {
		return p["crust"]
	}
	return p["text"]
}

// renderLoginColors writes the theme.conf [General] keys Main.qml reads. The
// background line is not here: apollo-sddm-sync adds it, because only it knows
// what the image ended up being called inside the theme directory.
func renderLoginColors(c Config) string {
	p := effectivePalette(c)
	accent := accentOr(c, p)

	var b strings.Builder
	b.WriteString("# Generated by apollo-settings — DO NOT EDIT BY HAND.\n")
	b.WriteString("# Regenerated on every wallpaper change; installed by apollo-sddm-sync.\n")
	for _, kv := range [][2]string{
		{"base", p["base"]},
		{"mantle", p["mantle"]},
		{"crust", p["crust"]},
		{"surface0", p["surface0"]},
		{"surface1", p["surface1"]},
		{"overlay1", p["overlay1"]},
		{"subtext0", p["subtext0"]},
		{"text", p["text"]},
		{"accent", accent},
		{"onAccent", readableOn(accent, p)},
		{"error", p["red"]},
	} {
		fmt.Fprintf(&b, "%s=%s\n", kv[0], kv[1])
	}
	return b.String()
}

// stageLoginColors writes that block into the cache. It is never an error for
// the login screen not to be installed — plenty of machines log in from a TTY —
// so the sync script, not this, decides whether anything reads it.
func stageLoginColors(c Config) error {
	path := stagedLoginColorsPath()
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return err
	}
	return os.WriteFile(path, []byte(renderLoginColors(c)), 0o644)
}
