package main

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

// rofiColorsPath is the generated file config.rasi's @theme points at. It
// chain-imports the base theme itself (see renderRofiColors) because this
// rofi version does not cascade multiple @theme lines in one config file —
// a second @theme resets everything to rofi's built-in defaults instead of
// layering on top.
func rofiColorsPath() string {
	home, _ := os.UserHomeDir()
	return filepath.Join(home, ".config", "rofi", "themes", "apollo-colors.rasi")
}

// A ~ path, not an absolute one: rofi expands it, and it keeps this app from
// writing anybody's home directory into a file.
const rofiBaseTheme = "~/.config/rofi/themes/catppuccin-mocha.rasi"

// renderRofiColors imports the base catppuccin theme, then overrides just
// the accent ("pink") variable it uses for the prompt icon and the
// selected-item border.
func renderRofiColors(c Config) string {
	var b strings.Builder
	b.WriteString("/* Generated by apollo-settings — DO NOT EDIT BY HAND. */\n")
	fmt.Fprintf(&b, "@theme %q\n", rofiBaseTheme)
	b.WriteString("* {\n")
	fmt.Fprintf(&b, "    pink: %s;\n", c.RofiAccent)
	b.WriteString("}\n")
	return b.String()
}

// applyRofi writes the override file. config.rasi's @theme points at it
// statically and is committed, so nothing here touches a tracked file — see
// .gitignore. Rofi re-reads its theme on every launch, so there is no reload.
func applyRofi(c Config) error {
	if err := os.MkdirAll(filepath.Dir(rofiColorsPath()), 0o755); err != nil {
		return err
	}
	return os.WriteFile(rofiColorsPath(), []byte(renderRofiColors(c)), 0o644)
}
