local cfg = require("lua.config")

hl.on("hyprland.start", function()
    hl.exec_cmd("awww-daemon")
    hl.exec_cmd("bash -c 'sleep 1 && awww restore'")
    hl.exec_cmd("qs -c caelestia")
    hl.exec_cmd("hypridle")
    hl.exec_cmd("hyprsunset")
    hl.exec_cmd("bash -c 'wl-paste --type text --watch cliphist store'")
    hl.exec_cmd("bash -c 'wl-paste --type image --watch cliphist store'")
    hl.exec_cmd("bash ~/.config/hypr/scripts/lockscreen-weather.sh")
    hl.exec_cmd("bash ~/.local/bin/wallpaper-thumb-sync.sh")
end)
