"""Every $variable a layout uses for a colour or a path must be defined.

hyprlock does not error on an unknown variable - it renders it as nothing,
which on a lock screen means black text on a black card with no clue why. So
this is checked rather than trusted.

Only value positions of known colour/path properties are inspected: telling a
hyprlang $var from a shell $var inside a cmd[...] string is not reliable, and
those are where the risk actually is.
"""
import pathlib, re, sys

PROPS = r'(?:border_)?color|inner_color|outer_color|font_color|shadow_color|path'
USE = re.compile(rf'^\s*(?:{PROPS})\s*=\s*\$([A-Za-z_][A-Za-z0-9_]*)\s*$')
DEF = re.compile(r'^\s*\$([A-Za-z_][A-Za-z0-9_]*)\s*=')

defined = set()
for f in ["config/matugen/templates/hyprlock-colors.conf.template",
          "config/hyprlock/assets.conf",
          "config/hypr/hyprlock.conf"]:
    for line in pathlib.Path(f).read_text().split("\n"):
        m = DEF.match(line)
        if m: defined.add(m.group(1))
defined.add("wall")   # wallpaper.conf, generated by hyprlock-wallpaper.sh

bad, checked = [], 0
for f in sorted(pathlib.Path("config/hyprlock/layouts").glob("*.conf")):
    for i, line in enumerate(f.read_text().split("\n"), 1):
        if line.lstrip().startswith("#"): continue
        m = USE.match(line)
        if not m: continue
        checked += 1
        if m.group(1) not in defined:
            bad.append(f"{f}:{i}: ${m.group(1)} is used but never defined")

# placeholder_text is pango markup, so its colour is a #hex inside a span
# rather than a colour property. Those variables need checking too.
PLACEHOLDER = re.compile(r'placeholder_text\s*=.*foreground="\$([A-Za-z_][A-Za-z0-9_]*)"')
for f in sorted(pathlib.Path("config/hyprlock/layouts").glob("*.conf")):
    for i, line in enumerate(f.read_text().split("\n"), 1):
        m = PLACEHOLDER.search(line)
        if m:
            checked += 1
            if m.group(1) not in defined:
                bad.append(f"{f}:{i}: ${m.group(1)} is used but never defined")

# An input field filled with an accent needs on-accent text. matugen's dark-mode
# accents are light pastels, so a light $fg here is unreadable - upstream's
# saturated reds tolerated white text and these do not.
FIELD = re.compile(r'^input-field\s*\{')
for f in sorted(pathlib.Path("config/hyprlock/layouts").glob("*.conf")):
    lines = f.read_text().split("\n")
    for s_ in [n for n, l in enumerate(lines) if FIELD.match(l)]:
        e = next((n for n in range(s_+1, len(lines)) if lines[n].strip() == "}"), len(lines)-1)
        blk = lines[s_:e+1]
        def val(prop):
            for l in blk:
                m = re.match(rf'\s*{prop}\s*=\s*\$(\w+)\s*$', l)
                if m: return m.group(1)
            return None
        inner, font = val("inner_color"), val("font_color")
        if inner and font and inner.startswith("accent") and not font.startswith("on_accent"):
            bad.append(f"{f}:{s_+1}: input-field is filled with ${inner} "
                       f"but its text is ${font}; accents are light, so this needs an $on_accent*")

# brace balance - a stray brace silently swallows the rest of a layout
for f in sorted(pathlib.Path("config/hyprlock/layouts").glob("*.conf")):
    t = "\n".join(l for l in f.read_text().split("\n") if not l.lstrip().startswith("#"))
    if t.count("{") != t.count("}"):
        bad.append(f"{f}: unbalanced braces ({t.count('{')} open, {t.count('}')} close)")

if bad:
    print("\n".join(bad)); sys.exit(1)
print(f"ok - {checked} colour/path references across 4 layouts, all defined; braces balanced")
